project_id = "aeyyzppqymrqmezbbcaq"

[functions.analyze-sentiment]
verify_jwt = false

[functions.extract-brands]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.tiktok-search]
verify_jwt = false

[functions.instagram-search]
verify_jwt = false

[functions.tiktok-sync]
verify_jwt = false

[functions.instagram-sync]
verify_jwt = false
